source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Scale_Example', :exclusive => true do
  pod "Scale", :path => "../"
end

target 'Scale_Tests', :exclusive => true do
  pod "Scale", :path => "../"

  
end
